# Import

In [1]:
import numpy as np
import scipy as sp
from scipy.interpolate import *
from numpy import *
import matplotlib.pyplot as plt
from matplotlib.pyplot import *

In [2]:
ga = np.genfromtxt('/home/axect/Desktop/GA2/HW_1_F_group.csv',delimiter=',')
ga2 = np.load('/home/axect/Desktop/GA2/HW_2_table.pickle')
ga3 = np.zeros(shape=(200,12))
for i in range(0,len(ga2)):
    for j in range(1,len(ga2[0])):
        ga3[i][j] = ga2[i][j]
ga3 = ga3[:,1:]
ga3_c = np.zeros(shape=(200,1))
for i in range(0,len(ga3_c)):
    unique,pos = np.unique(ga3[i],return_inverse=True)
    counts = np.bincount(pos)
    maxpos = counts.argmax()
    ga3_c[i] = unique[maxpos]
ga3_t = np.concatenate((ga3,ga3_c),axis=1)
ga3_tempo = ga3_t[:,6].reshape(200,1)
ga_config = np.concatenate((ga3_tempo,ga3_c),axis=1)
ga3_oh = ga3_t[:,0].reshape(200,1)
ga2_config = np.concatenate((ga3_tempo,ga3_oh),axis=1)

classes=[10,20,31,32,33,34,41,42,43,44,50]
classes2=['E', 'S0', 'Sa', 'Sb', 'Sc', 'Sd', 'SBa', 'SBb', 'SBc', 'SBd', 'Irr']
classes3=['E','0','a','b','c','d','Irr']
classes4=[-0.5,0,0.5]
classes_group=['Oh','A','B','C','D','E','F','G','H','I','J']


In [3]:
ga3[0]

array([ 10.,  10.,  20.,  10.,  20.,  10.,  10.,  20.,  20.,  20.,  20.])

# Obtain Confused Index

In [4]:
for i in classes:
    locals()["b_"+str(i)] = 0;
    for j in classes:
        locals()["a_"+str(i)+"_"+str(j)] = 0;
for i in range(0,len(ga[:,0])):
    for k in classes:
        if ga[i][5] == k:
            for j in classes:
                if j != ga[i][5]:
                    locals()["a_"+str(k)+"_"+str(j)] =(locals()["a_"+str(k)+"_"+str(j)]
                                                       + (ga[i]==j).sum())
            if k < 40:
                locals()["b_"+str(k)] = (locals()["b_"+str(k)]
                                         + ((ga[i]>40) & (ga[i]!=50)).sum())
            else:
                locals()["b_"+str(k)] = locals()["b_"+str(k)] + (ga[i]<40).sum()
                
Total = np.zeros(shape=(11,11))
Total_bar = np.zeros(shape=(11))
CONF = np.zeros(shape=(11,11))
CONF_bar = np.zeros(shape=(11))
Ratio = np.zeros(shape=(11,11))
Ratio_bar = np.zeros(shape=(11))
for s in range(0,11):
    Total_bar[s] = (ga3_tempo==classes[s]).sum()
    CONF_bar[s] = locals()["b_"+str(classes[s])]
    Ratio_bar[s] = np.around(CONF_bar[s]/Total_bar[s]*100)
    for t in range(0,11):
        Total[s,t] = (ga[:,5]==classes[s]).sum() + (ga[:,5]==classes[t]).sum()
        CONF[s,t] = (locals()["a_"+str(classes[s])+"_"+str(classes[t])] 
                     + locals()["a_"+str(classes[t])+"_"+str(classes[s])])
        Ratio[s,t] = np.around(CONF[s,t]/Total[s,t]*100)

/home/axect/.local/lib/python2.7/site-packages/ipykernel/__main__.py:14: RuntimeWarning: invalid value encountered in greater
/home/axect/.local/lib/python2.7/site-packages/ipykernel/__main__.py:16: RuntimeWarning: invalid value encountered in less


In [5]:
CONF

array([[  0.,  43.,   1.,   0.,   1.,   0.,   2.,   0.,   0.,   0.,   1.],
       [ 43.,   0.,  14.,   4.,   0.,   0.,   7.,   2.,   0.,   0.,   1.],
       [  1.,  14.,   0.,  22.,  10.,   1.,  18.,   3.,   1.,   0.,   2.],
       [  0.,   4.,  22.,   0.,  27.,   5.,   4.,  13.,   6.,   0.,   4.],
       [  1.,   0.,  10.,  27.,   0.,   8.,   2.,   8.,   8.,   2.,   3.],
       [  0.,   0.,   1.,   5.,   8.,   0.,   0.,   1.,   4.,   7.,   4.],
       [  2.,   7.,  18.,   4.,   2.,   0.,   0.,  15.,   6.,   3.,   2.],
       [  0.,   2.,   3.,  13.,   8.,   1.,  15.,   0.,  13.,   2.,   0.],
       [  0.,   0.,   1.,   6.,   8.,   4.,   6.,  13.,   0.,   5.,   1.],
       [  0.,   0.,   0.,   0.,   2.,   7.,   3.,   2.,   5.,   0.,   5.],
       [  1.,   1.,   2.,   4.,   3.,   4.,   2.,   0.,   1.,   5.,   0.]])

In [6]:
Total

array([[ 90.,  68.,  68.,  70.,  64.,  53.,  62.,  64.,  56.,  50.,  50.],
       [ 68.,  46.,  46.,  48.,  42.,  31.,  40.,  42.,  34.,  28.,  28.],
       [ 68.,  46.,  46.,  48.,  42.,  31.,  40.,  42.,  34.,  28.,  28.],
       [ 70.,  48.,  48.,  50.,  44.,  33.,  42.,  44.,  36.,  30.,  30.],
       [ 64.,  42.,  42.,  44.,  38.,  27.,  36.,  38.,  30.,  24.,  24.],
       [ 53.,  31.,  31.,  33.,  27.,  16.,  25.,  27.,  19.,  13.,  13.],
       [ 62.,  40.,  40.,  42.,  36.,  25.,  34.,  36.,  28.,  22.,  22.],
       [ 64.,  42.,  42.,  44.,  38.,  27.,  36.,  38.,  30.,  24.,  24.],
       [ 56.,  34.,  34.,  36.,  30.,  19.,  28.,  30.,  22.,  16.,  16.],
       [ 50.,  28.,  28.,  30.,  24.,  13.,  22.,  24.,  16.,  10.,  10.],
       [ 50.,  28.,  28.,  30.,  24.,  13.,  22.,  24.,  16.,  10.,  10.]])

In [7]:
Ratio

array([[  0.,  63.,   1.,   0.,   2.,   0.,   3.,   0.,   0.,   0.,   2.],
       [ 63.,   0.,  30.,   8.,   0.,   0.,  18.,   5.,   0.,   0.,   4.],
       [  1.,  30.,   0.,  46.,  24.,   3.,  45.,   7.,   3.,   0.,   7.],
       [  0.,   8.,  46.,   0.,  61.,  15.,  10.,  30.,  17.,   0.,  13.],
       [  2.,   0.,  24.,  61.,   0.,  30.,   6.,  21.,  27.,   8.,  12.],
       [  0.,   0.,   3.,  15.,  30.,   0.,   0.,   4.,  21.,  54.,  31.],
       [  3.,  18.,  45.,  10.,   6.,   0.,   0.,  42.,  21.,  14.,   9.],
       [  0.,   5.,   7.,  30.,  21.,   4.,  42.,   0.,  43.,   8.,   0.],
       [  0.,   0.,   3.,  17.,  27.,  21.,  21.,  43.,   0.,  31.,   6.],
       [  0.,   0.,   0.,   0.,   8.,  54.,  14.,   8.,  31.,   0.,  50.],
       [  2.,   4.,   7.,  13.,  12.,  31.,   9.,   0.,   6.,  50.,   0.]])

In [8]:
CONF_bar

array([  1.,   5.,  15.,  11.,  11.,   7.,  12.,  13.,   9.,   4.,   5.])

In [9]:
Total_bar

array([ 45.,  22.,  22.,  26.,  20.,   8.,  17.,  19.,  11.,   5.,   5.])

In [10]:
Ratio_bar

array([   2.,   23.,   68.,   42.,   55.,   88.,   71.,   68.,   82.,
         80.,  100.])

# Determine Distance

## Obtain Relative Confused index

In [11]:
conf_rel = np.zeros(shape=(6,1))
for i in range(0,len(conf_rel)):
    if i == 0:
        conf_rel[i] = CONF[i+1,i]
    elif i == 1:
        conf_rel[i] = CONF[i+1,i] + CONF[i+5,i]
    elif i<= 4:
        conf_rel[i] = CONF[i+1,i]+CONF[i+5,i+4]
    else:
        conf_rel[i] = CONF[10,9] + CONF[5,10]

In [12]:
total_rel = np.zeros(shape=(6,1))
for i in range(0,len(total_rel)):
    if i == 0:
        total_rel[i] = Total[i+1,i]
    elif i == 1:
        total_rel[i] = Total[i+1,i] + Total[i+5,i] - Total[i,i]/2
    elif i<= 4:
        total_rel[i] = Total[i+1,i]+ Total[i+5,i+4]
    else:
        total_rel[i] = Total[10,9] + Total[5,10] - Total[10,10]/2

In [13]:
print conf_rel
print total_rel

[[ 43.]
 [ 21.]
 [ 37.]
 [ 40.]
 [ 13.]
 [  9.]]
[[ 68.]
 [ 63.]
 [ 84.]
 [ 74.]
 [ 43.]
 [ 18.]]


In [14]:
ratio_rel = conf_rel/total_rel

In [15]:
ratio_rel

array([[ 0.63235294],
       [ 0.33333333],
       [ 0.44047619],
       [ 0.54054054],
       [ 0.30232558],
       [ 0.5       ]])

In [16]:
confbar_rel = np.zeros(shape=(7,1))
for i in range(0,len(confbar_rel)):
    if i <= 1:
        confbar_rel[i] = CONF_bar[i]
    elif i<=5:
        confbar_rel[i] = CONF_bar[i] + CONF_bar[i+4]
    else:
        confbar_rel[i] = CONF_bar[10]

In [17]:
totalbar_rel = np.zeros(shape=(7,1))
for i in range(0,len(totalbar_rel)):
    if i <= 1:
        totalbar_rel[i] = Total_bar[i]
    elif i<=5:
        totalbar_rel[i] = Total_bar[i] + Total_bar[i+4]
    else:
        totalbar_rel[i] = Total_bar[10]

In [18]:
confbar_rel

array([[  1.],
       [  5.],
       [ 27.],
       [ 24.],
       [ 20.],
       [ 11.],
       [  5.]])

In [19]:
totalbar_rel

array([[ 45.],
       [ 22.],
       [ 39.],
       [ 45.],
       [ 31.],
       [ 13.],
       [  5.]])

In [20]:
ratiobar_rel = confbar_rel/totalbar_rel

In [21]:
ratiobar_rel

array([[ 0.02222222],
       [ 0.22727273],
       [ 0.69230769],
       [ 0.53333333],
       [ 0.64516129],
       [ 0.84615385],
       [ 1.        ]])

In [22]:
dist_rel = 1-ratio_rel
distbar_rel = 1-ratiobar_rel

In [23]:
dist_rel

array([[ 0.36764706],
       [ 0.66666667],
       [ 0.55952381],
       [ 0.45945946],
       [ 0.69767442],
       [ 0.5       ]])

## Hangyul's Data

In [24]:
conf_han = np.array([0.90762, 0.96, 0.616667,0.697368, 0.833333, 0.66667])
distbar_rel = 1 - ratiobar_rel
dist_rel = conf_han.reshape(6,1)

In [25]:
dist_rel

array([[ 0.90762 ],
       [ 0.96    ],
       [ 0.616667],
       [ 0.697368],
       [ 0.833333],
       [ 0.66667 ]])

## Interpolation of distance of bar

In [26]:
x=np.array([0,1,2,3,4,5,6]).squeeze()
x_tem = np.array([0,6]).squeeze()
distbar_tem = np.array([distbar_rel[0],distbar_rel[6]]).squeeze()
z=np.linspace(0,6,num=101)
y_tem=interp1d(x_tem,distbar_tem,kind = 'linear')(z) #Lagrange Interpolation of Distance of bar
y=interp1d(x_tem,distbar_tem,kind = 'linear')(x)
plt.figure()
Interp_Li = plt.plot(z,y_tem, label='Linear Interpolation')
Index_bar = plt.scatter(x,distbar_rel, label='Bar index')
plt.legend((Interp_Li, Index_bar),('Linear Interpolation','Bar index'),scatterpoints=1)
plt.title('Interpolation of distance of bar', fontsize=14, fontweight='bold')
plt.xticks(x,classes3)
plt.show()

/home/axect/.local/lib/python2.7/site-packages/matplotlib/legend.py:633: UserWarning: Legend does not support [<matplotlib.lines.Line2D object at 0x7fa14e200590>] instances.
A proxy artist may be used instead.
See: http://matplotlib.org/users/legend_guide.html#using-proxy-artist
  "#using-proxy-artist".format(orig_handle)


## Arrange Points

In [27]:
dist_rel

array([[ 0.90762 ],
       [ 0.96    ],
       [ 0.616667],
       [ 0.697368],
       [ 0.833333],
       [ 0.66667 ]])

In [28]:
distbar_rel

array([[ 0.97777778],
       [ 0.77272727],
       [ 0.30769231],
       [ 0.46666667],
       [ 0.35483871],
       [ 0.15384615],
       [ 0.        ]])

### Our Data

In [29]:
ga3_x = np.zeros(shape=(200,1))
ga3_y = np.zeros(shape=(200,1))
d=np.zeros(shape=[7,1])
for j in range(0,len(classes3)):
    if j==0:
        d[j]=0
        print d[j]
    elif j<=5:
        d[j]=d[j-1]+dist_rel[j-1]
        print d[j]
    else:
        d[6] = d[5] + dist_rel[5]
        print d[6]

d_tem = np.array([d[0],d[6]]).squeeze()
db_tem = distbar_tem*17/45

for i in range(0,len(ga3_tempo)):
    for j in range(0,len(classes)):
        if j==0:
            if ga3_tempo[i] == classes[j]:
                ga3_x[i] = d[0]
                ga3_y[i] = -interp1d(d_tem, db_tem)(d[0])
        elif j<=5:
            if ga3_tempo[i] == classes[j]:
                ga3_x[i] = d[j]
                ga3_y[i] = -interp1d(d_tem, db_tem)(d[j])
        elif j<10:
            if ga3_tempo[i] == classes[j]:
                ga3_x[i] = d[j-4]
                ga3_y[i] = +interp1d(d_tem, db_tem)(d[j-4])
        else:
            if ga3_tempo[i] == classes[j]:
                ga3_x[i]=d[6]
                ga3_y[i]=interp1d(d_tem, db_tem)(d[6])

ga_config3 = np.zeros(shape=(200,1))
for i in range(0,len(ga_config3)):
    ga_config3[i] = (ga3_tempo==ga3_tempo[i]).sum()
fig = plt.figure()
fig.suptitle('Rearrange our points', fontsize=14, fontweight='bold')
ax=fig.add_subplot(111)
ax.set_xlabel('Morphology')
ax.set_ylabel('Bar')
ax.scatter(ga3_x,ga3_y,s=ga_config3*15,facecolor='none',edgecolor='red',alpha=0.25,label='Our data')
ax.legend(loc='upper right',scatterpoints=1)
plt.xticks(d.squeeze(),classes3)
plt.axis([-0.4, 5, -1, 1])
plt.show()

[ 0.]
[ 0.90762]
[ 1.86762]
[ 2.484287]
[ 3.181655]
[ 4.014988]
[ 4.681658]


### Oh's data

In [30]:
ga3_x2 = np.zeros(shape=(200,1))
ga3_y2 = np.zeros(shape=(200,1))

for i in range(0,len(ga3_tempo)):
    for j in range(0,len(classes)):
        if j==0:
            if ga3_oh[i] == classes[j]:
                ga3_x2[i] = d[0]
                ga3_y2[i] = -interp1d(d_tem, db_tem)(d[0])
        elif j<=5:
            if ga3_oh[i] == classes[j]:
                d[j] = d[j-1] + dist_rel[j-1]
                ga3_x2[i] = d[j]
                ga3_y2[i] = -interp1d(d_tem, db_tem)(d[j])
        elif j<10:
            if ga3_oh[i] == classes[j]:
                ga3_x2[i] = d[j-4]
                ga3_y2[i] = +interp1d(d_tem, db_tem)(d[j-4])
        else:
            if ga3_oh[i] == classes[j]:
                d[6] = d[5] + dist_rel[5]
                ga3_x2[i]=d[6]
                ga3_y2[i]=interp1d(d_tem, db_tem)(d[6])
ga2_config3 = np.zeros(shape=(200,1))
for i in range(0,len(ga_config3)):
    ga2_config3[i] = (ga3_oh==ga3_oh[i]).sum()

In [31]:
fig = plt.figure()
fig.suptitle('Rearrange points', fontsize=14, fontweight='bold')
ax=fig.add_subplot(111)
ax.set_xlabel('Morphology')
ax.set_ylabel('Bar')
ax.scatter(ga3_x,ga3_y,s=ga_config3*15,facecolor='none',edgecolors='red',alpha=0.25,label='Our data')
ax.scatter(ga3_x2,ga3_y2,s=ga2_config3*15,facecolor='none',edgecolors='blue',alpha=0.25,label='Oh et al')
ax.legend(loc='upper right',scatterpoints=1)
plt.xticks(d.squeeze(),classes3)
plt.axis([-0.4, 5, -1, 1])
plt.show()

### All Groups data

In [32]:
for i in range(0,len(ga3[0])):
    locals()["ga3_x_"+str(i)] = np.zeros(shape=(200,1))
    locals()["ga3_y_"+str(i)] = np.zeros(shape=(200,1))

for k in range(0,len(ga3[0])):
    for i in range(0,len(ga3_tempo)):
        for j in range(0,len(classes)):
            if j==0:
                if ga3[i,k] == classes[j]:
                    locals()["ga3_x_"+str(k)][i] = d[0]
                    locals()["ga3_y_"+str(k)][i] = -interp1d(d_tem, db_tem)(d[0])
            elif j<=5:
                if ga3[i,k] == classes[j]:
                    d[j] = d[j-1] + dist_rel[j-1]
                    locals()["ga3_x_"+str(k)][i] = d[j]
                    locals()["ga3_y_"+str(k)][i] = -interp1d(d_tem, db_tem)(d[j])
            elif j<10:
                if ga3[i,k] == classes[j]:
                    locals()["ga3_x_"+str(k)][i] = d[j-4]
                    locals()["ga3_y_"+str(k)][i] = +interp1d(d_tem, db_tem)(d[j-4])
            else:
                if ga3[i,k] == classes[j]:
                    d[6] = d[5] + dist_rel[5]
                    locals()["ga3_x_"+str(k)][i]=d[6]
                    locals()["ga3_y_"+str(k)][i]=interp1d(d_tem, db_tem)(d[6])
for k in range(0,len(ga3[0])):
    locals()["config_"+str(k)] = np.zeros(shape=(200,1))
    for i in range(0,len(ga3_tempo)):
        locals()["config_"+str(k)][i] = (ga3[:,k]==ga3[i,k]).sum()

# Matching data

## The number of matched data

In [33]:
for i in classes:
    locals()["matched_"+str(i)] = ((ga3_tempo==ga3_oh)&(ga3_tempo==i)).sum()
    print locals()["matched_"+str(i)]

44
14
6
12
15
2
3
6
4
1
1


## Our data to Oh et al for each types

In [34]:
ga3_set = np.concatenate((ga3_x,ga3_y),axis=1)
ga3_set2 = np.concatenate((ga3_x2,ga3_y2),axis=1)

In [35]:
for j in classes:
    locals()["total_"+str(j)] = 0;
    for i in range(0,len(ga3_x)):
        if ga3_tempo[i,0]==j:
            locals()["total_"+str(j)] = (locals()["total_"+str(j)] 
                                         + sqrt((ga3_set[i,0] - ga3_set2[i,0])**2 + (ga3_set[i,1]-ga3_set2[i,1])**2))
    locals()["mean_"+str(j)] = locals()["total_"+str(j)]/200;
    print locals()["mean_"+str(j)]

0.00936712070609
0.0369430549722
0.0544035095412
0.0477674257375
0.0168856800679
0.0232499395586
0.0492741366912
0.042382993582
0.0204192940902
0.0142845616465
0.0294113556693


## All groups data to oh et al

In [36]:
for k in range(0,len(ga3[0])):
    locals()["ga3_set_"+str(k)] = np.concatenate((locals()["ga3_x_"+str(k)],locals()["ga3_y_"+str(k)]),axis=1)
    locals()["total_d_"+str(k)] = 0
    for i in range(0,len(ga3_x)):
        locals()["total_d_"+str(k)] = (locals()["total_d_"+str(k)] + sqrt((locals()["ga3_set_"+str(k)][i,0] - ga3_set2[i,0])**2
                                                                         + (locals()["ga3_set_"+str(k)][i,1] - ga3_set2[i,1])**2))
    locals()["mean_d_"+str(k)] = locals()["total_d_"+str(k)]/200
    print classes_group[k], locals()["mean_d_"+str(k)]

Oh 0.0
A 0.511687081715
B 0.3449409896
C 0.362472323201
D 0.347588218029
E 0.568113984341
F 0.344389072263
G 0.388583085553
H 0.421787147536
I 0.360581448875
J 0.269728797459


## All groups data to Oh et al for each types

In [37]:
for k in range(0,len(classes_group)):
    for j in classes:
        locals()["total_"+str(classes_group[k])+str(j)] = 0
        for i in range(0,len(ga3_x)):
            if ga3[i,k]==j:
                locals()["total_"+str(classes_group[k])+str(j)] = (locals()["total_"+str(classes_group[k])+str(j)]
                                                                   + sqrt(((locals()["ga3_set_"+str(k)][i,0] - ga3_set2[i,0])**2 + (locals()["ga3_set_"+str(k)][i,1]-ga3_set2[i,1])**2)))
        locals()["mean_"+str(classes_group[k])+str(j)] = locals()["total_"+str(classes_group[k])+str(j)]/200

In [38]:
for j in classes:
    for k in range(0,len(classes_group)):
        print j, classes_group[k], locals()["mean_"+str(classes_group[k])+str(j)]

10 Oh 0.0
10 A 0.0514414832175
10 B 0.01365661017
10 C 0.0457847478262
10 D 0.0275759342661
10 E 0.0822523798689
10 F 0.00936712070609
10 G 0.00455220339002
10 H 0.021564444795
10 I 0.0275759342661
10 J 0.0182088135601
20 Oh 0.0
20 A 0.121008972632
20 B 0.0469537175269
20 C 0.0182088135601
20 D 0.0795465167102
20 E 0.102882966435
20 F 0.0369430549722
20 G 0.0556772963844
20 H 0.116199255302
20 I 0.0621258449283
20 J 0.0366803410462
31 Oh 0.0
31 A 0.105258309267
31 B 0.0470654731253
31 C 0.0420318403056
31 D 0.0482176749234
31 E 0.0794486430174
31 F 0.0544035095412
31 G 0.064616978606
31 H 0.0522851494438
31 I 0.0413242375833
31 J 0.0258829348894
32 Oh 0.0
32 A 0.0585121830787
32 B 0.0580714863653
32 C 0.0160063847149
32 D 0.0470202608875
32 E 0.0449120024496
32 F 0.0477674257375
32 G 0.0243609293975
32 H 0.0425000864663
32 I 0.0439877952055
32 J 0.0157244304943
33 Oh 0.0
33 A 0.0203833563792
33 B 0.0313387129729
33 C 0.0215668584253
33 D 0.0116765309801
33 E 0.0128600330262
33 F 0.0168