In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
ga = np.genfromtxt('/home/axect/Desktop/GA2/HW_1_F_group.csv',delimiter=',')
ga2 = np.load('/home/axect/Desktop/GA2/HW_2_table.pickle')

In [3]:
ga3 = np.zeros(shape=(200,12))
for i in range(0,len(ga2)):
    for j in range(1,len(ga2[0])):
        ga3[i][j] = ga2[i][j]

In [4]:
ga

array([[ nan,  10.,  10., ...,  20.,  10.,  10.],
       [ nan,  10.,  10., ...,  10.,  10.,  10.],
       [ nan,  41.,  31., ...,  31.,  31.,  31.],
       ..., 
       [ nan,  43.,  41., ...,  42.,  43.,  42.],
       [ nan,  41.,  41., ...,  41.,  41.,  41.],
       [ nan,  33.,  42., ...,  33.,  33.,  33.]])

In [5]:
ga0=ga[:,6]

In [6]:
ga3

array([[  0.,  10.,  10., ...,  20.,  20.,  20.],
       [  0.,  10.,  10., ...,  20.,  10.,  10.],
       [  0.,  32.,  31., ...,  31.,  32.,  32.],
       ..., 
       [  0.,  42.,  42., ...,  42.,  42.,  43.],
       [  0.,  41.,  20., ...,  41.,  41.,  41.],
       [  0.,  33.,  32., ...,  33.,  33.,  33.]])

In [7]:
ga3 = ga3[:,1:-1]

In [8]:
ga3

array([[ 10.,  10.,  20., ...,  20.,  20.,  20.],
       [ 10.,  10.,  10., ...,  10.,  20.,  10.],
       [ 32.,  31.,  32., ...,  32.,  31.,  32.],
       ..., 
       [ 42.,  42.,  50., ...,  41.,  42.,  42.],
       [ 41.,  20.,  41., ...,  41.,  41.,  41.],
       [ 33.,  32.,  33., ...,  33.,  33.,  33.]])

In [9]:
ga3[0]

array([ 10.,  10.,  20.,  10.,  20.,  10.,  10.,  20.,  20.,  20.])

In [10]:
ga3_c = np.zeros(shape=(200,1))
for i in range(0,len(ga3_c)):
    unique,pos = np.unique(ga3[i],return_inverse=True)
    counts = np.bincount(pos)
    maxpos = counts.argmax()
    ga3_c[i] = unique[maxpos]

# Sanity check by all data (Oh + All group data)

In [11]:
ga3_t = np.concatenate((ga3,ga3_c),axis=1)

In [12]:
ga3_t

array([[ 10.,  10.,  20., ...,  20.,  20.,  10.],
       [ 10.,  10.,  10., ...,  20.,  10.,  10.],
       [ 32.,  31.,  32., ...,  31.,  32.,  31.],
       ..., 
       [ 42.,  42.,  50., ...,  42.,  42.,  42.],
       [ 41.,  20.,  41., ...,  41.,  41.,  41.],
       [ 33.,  32.,  33., ...,  33.,  33.,  33.]])

In [13]:
ga_t = np.concatenate((ga,ga3_c),axis=1)

In [14]:
ga_t

array([[ nan,  10.,  10., ...,  10.,  10.,  10.],
       [ nan,  10.,  10., ...,  10.,  10.,  10.],
       [ nan,  41.,  31., ...,  31.,  31.,  31.],
       ..., 
       [ nan,  43.,  41., ...,  43.,  42.,  42.],
       [ nan,  41.,  41., ...,  41.,  41.,  41.],
       [ nan,  33.,  42., ...,  33.,  33.,  33.]])

In [15]:
ga_t[0]

array([ nan,  10.,  10.,  20.,  20.,  10.,  10.,  10.])

In [16]:
matched_us = (ga_t[:,5]==ga_t[:,7]).sum()
matched_ma = (ga_t[:,6]==ga_t[:,7]).sum()

In [17]:
print(matched_us); print(matched_ma)

166
142


In [18]:
for i in range(0,len(ga3_t[0])-1):
    locals()["matched_"+str(i)] = (ga3_t[:,i]==ga3_t[:,10]).sum()
    print locals()["matched_"+str(i)]

126
122
138
130
140
115
167
138
132
141


In [19]:
(ga3_t[:,10]==ga3_c[:,0]).sum()

200

In [20]:
(ga3_t[:,6]==ga3_c[:,0]).sum()

167

In [21]:
ga3_tempo = ga3_t[:,6]

In [22]:
ga3_tempo = ga3_tempo.reshape(200,1)

In [23]:
ga_config = np.concatenate((ga3_tempo,ga3_c),axis=1)

In [24]:
ga_config2 = np.zeros(shape=(200,1))
len(ga_config2)

200

In [25]:
classes=[10,20,31,32,33,34,41,42,43,44,50]
classes2=['E', 'S0', 'Sa', 'Sb', 'Sc', 'Sd', 'SBa', 'SBb', 'SBc', 'SBd', 'Irr']

In [26]:
for i in range(0,len(ga_config2)):
    ga_config2[i] = (((ga_config[:,0]==ga_config[i,0])
                      &(ga_config[:,1]==ga_config[i,1])).sum())

ga3_x = np.zeros(shape=(200,1))
ga3_y = np.zeros(shape=(200,1))
for i in range(0,len(ga_config2)):
    for j in range(0,len(classes)):
        if ga3_tempo[i] == classes[j]:
            ga3_y[i] = j
        if ga3_c[i] == classes[j]:
            ga3_x[i] = j
x=[0,1,2,3,4,5,6,7,8,9,10]
y=[0,1,2,3,4,5,6,7,8,9,10]
fig = plt.figure()
fig.suptitle('Sanity check by all groups data', fontsize=14, fontweight='bold')

ax=fig.add_subplot(111)
ax.set_xlabel('All groups data')
ax.set_ylabel('Our data')
ax.plot(x,y,'k--')
ax.scatter(ga3_x,ga3_y,s=ga_config2*30,facecolors='none',alpha=0.5)

percentage2=ga_config2/2
percentage2=np.reshape(percentage2,200)
percentage2=percentage2.astype(int)

for i, txt in enumerate(percentage2):
    if percentage2[i]>5:
        ax.annotate('{}%'.format(txt),(ga3_x[i],ga3_y[i]),  ha='center',va='center',size=8)

plt.xticks(x,classes2)
plt.yticks(y,classes2)
plt.show()

# Sanity Check Image Processing (All Groups)

In [27]:
ga0_tempo = ga_t[:,6]
ga0_tempo = ga0_tempo.reshape(200,1)
ga0_config = np.concatenate((ga0_tempo,ga3_c),axis=1)

In [28]:
ga0_config2=np.zeros(shape=(200,1))

In [29]:
for i in range(0,len(ga0_config2)):
    ga0_config2[i] = (((ga0_config[:,0]==ga0_config[i,0])
                      &(ga0_config[:,1]==ga0_config[i,1])).sum())

ga0_x = np.zeros(shape=(200,1))
ga0_y = np.zeros(shape=(200,1))
for i in range(0,len(ga0_config2)):
    for j in range(0,len(classes)):
        if ga0_tempo[i] == classes[j]:
            ga0_y[i] = j
        if ga3_c[i] == classes[j]:
            ga0_x[i] = j
x=[0,1,2,3,4,5,6,7,8,9,10]
y=[0,1,2,3,4,5,6,7,8,9,10]
fig = plt.figure()
fig.suptitle('Sanity check Image Processing vs all groups data', fontsize=14, fontweight='bold')

ax=fig.add_subplot(111)
ax.set_xlabel('All groups data')
ax.set_ylabel('Our data')
ax.plot(x,y,'k--')
ax.scatter(ga0_x,ga0_y,s=ga0_config2*30,facecolors='none',alpha=0.5)

percentage0=ga0_config2/2
percentage0=np.reshape(percentage0,200)
percentage0=percentage0.astype(int)

for i, txt in enumerate(percentage0):
    if percentage0[i]>5:
        ax.annotate('{}%'.format(txt),(ga0_x[i],ga0_y[i]),  ha='center',va='center',size=8)

plt.xticks(x,classes2)
plt.yticks(y,classes2)
plt.show()

# Sanity check by Oh et al

In [30]:
ga3_oh = ga3_t[:,0].reshape(200,1)

In [31]:
matched2_us = (ga3_tempo==ga3_oh).sum()
matched2_ma = (ga0_tempo==ga3_oh).sum()
print matched2_us; print matched2_ma

108
156


In [32]:
ga2_config = np.concatenate((ga3_tempo,ga3_oh),axis=1)
ga2_config2 = np.zeros(shape = (200,1))

In [33]:
for i in range(0,len(ga2_config)):
    ga2_config2[i] = (((ga2_config[:,0]==ga2_config[i,0])
                       &(ga2_config[:,1]==ga2_config[i,1])).sum())

ga3_x2 = np.zeros(shape=(200,1))
ga3_y2 = np.zeros(shape=(200,1))
for i in range(0,len(ga2_config2)):
    for j in range(0,len(classes)):
        if ga3_tempo[i] == classes[j]:
            ga3_y2[i] = j
        if ga3_oh[i] == classes[j]:
            ga3_x2[i] = j
x=[0,1,2,3,4,5,6,7,8,9,10]
y=[0,1,2,3,4,5,6,7,8,9,10]
fig2 = plt.figure()
fig2.suptitle('Sanity check by Oh et al', fontsize=14, fontweight='bold')

ax2=fig2.add_subplot(111)
ax2.set_xlabel('Oh et al')
ax2.set_ylabel('Our data')
ax2.plot(x,y,'k--')
ax2.scatter(ga3_x2,ga3_y2,s=ga2_config2*30,facecolors='none',alpha=0.5)

percentage2=ga2_config2/2
percentage2=np.reshape(percentage2,200)
percentage2=percentage2.astype(int)

for i, txt in enumerate(percentage2):
    if percentage2[i]>3:
        ax2.annotate('{}%'.format(txt),(ga3_x2[i],ga3_y2[i]),  ha='center',va='center',size=8)

plt.xticks(x,classes2)
plt.yticks(y,classes2)
plt.show()

In [34]:
for i in classes:
    locals()["matched_us"+str(i)] = ((ga3_tempo == i)&(i == ga3_oh)).sum()
    print locals()["matched_us"+str(i)]

44
14
6
12
15
2
3
6
4
1
1


# Sanity Check Image Processing (Oh et al)

In [35]:
ga1_config = np.concatenate((ga0_tempo,ga3_oh),axis=1)
ga1_config2 = np.zeros(shape = (200,1))

In [36]:
for i in range(0,len(ga1_config)):
    ga1_config2[i] = (((ga1_config[:,0]==ga1_config[i,0])
                       &(ga1_config[:,1]==ga1_config[i,1])).sum())

ga0_x2 = np.zeros(shape=(200,1))
ga0_y2 = np.zeros(shape=(200,1))
for i in range(0,len(ga1_config2)):
    for j in range(0,len(classes)):
        if ga0_tempo[i] == classes[j]:
            ga0_y2[i] = j
        if ga3_oh[i] == classes[j]:
            ga0_x2[i] = j
x=[0,1,2,3,4,5,6,7,8,9,10]
y=[0,1,2,3,4,5,6,7,8,9,10]
fig2 = plt.figure()
fig2.suptitle('Sanity check Image Processing vs Oh et al', fontsize=14, fontweight='bold')

ax2=fig2.add_subplot(111)
ax2.set_xlabel('Oh et al')
ax2.set_ylabel('Our data')
ax2.plot(x,y,'k--')
ax2.scatter(ga0_x2,ga0_y2,s=ga1_config2*30,facecolors='none',alpha=0.5)

percentage2=ga1_config2/2
percentage2=np.reshape(percentage2,200)
percentage2=percentage2.astype(int)

for i, txt in enumerate(percentage2):
    if percentage2[i]>3:
        ax2.annotate('{}%'.format(txt),(ga0_x2[i],ga0_y2[i]),  ha='center',va='center',size=8)

plt.xticks(x,classes2)
plt.yticks(y,classes2)
plt.show()